eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/infonal
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    function:
      definition: orderEvents
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        productEvents-out-0:
          destination: product-topic
        orderEvents-in-0:
          destination: order-topic
          contentType: application/json
          group: product-service
          consumer:
            enableDlq: true
            auto-offset-reset: earliest
            maxAttempts: 3

  datasource:
    url: jdbc:postgresql://localhost:5050/product_service
    username: postgres
    password: product_service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

