eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8585/realms/infonal
  datasource:
    url: jdbc:postgresql://localhost:5433/product_service
    username: postgres
    password: product_service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    function:
      definition: productEvents
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        productCreated-out-0:
          destination: product-topic

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
