spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ozgur48/microservice-product-management.git
          default-label: main
          search-paths:
            - configurations
            - configurations/{application}
          clone-on-start: true
          force-pull: true
          password: <token>
server:
  port: 8787